on: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v4
    
    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net
        username: if0_39732046
        password: ${{ secrets.ftp_password }}
        server-dir: htdocs/

    
    # - name: Create Database
    #   # run: |
      #   mkdir -p laravel/database
      #   touch database/database.sqlite
    # - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
    #   env:
    #       DB_CONNECTION: sqlite
    #       DB_DATABASE: content/database/database.sqlite
    #   run: php artisan test